public enum GameState {
    PLAYER_MUST_CHOOSE_NUMBER_OF_PLAYERS,
    PLAYER_MUST_PICK_A_TILE,
    PLAYER_MUST_CHOOSE_POSITION_FOR_DASH_TILE,
    PLAYER_MUST_CHOOSE_POSITION_FOR_DASH_TILE_RELATIVE_TO_CHOSEN_TILE,
    PLAYER_MUST_CHOOSE_OPPONENT_TILE,
    PLAYER_MUST_GUESS_OPPONENT_TILE,
    PLAYER_MUST_CLICK_CONTINUE,
}
